package br.com.mapeiaia.rotacerta

object FarolCoordinateResolution0697 {
    const val CONTRACT_MARKER = "FAROL_COORDINATE_RESOLUTION_0697"
    const val STARTED_MARKER = "FAROL_COORDINATE_RESOLUTION_STARTED_0697"
    const val PLATFORM_STARTED_MARKER = "FAROL_PLATFORM_GEOCODER_STARTED_0697"
    const val PLATFORM_TIMEOUT_MARKER = "FAROL_PLATFORM_GEOCODER_TIMEOUT_0697"
    const val FALLBACK_MARKER = "FAROL_COORDINATE_PROVIDER_FALLBACK_0697"
    const val RESOLVED_MARKER = "FAROL_COORDINATE_RESOLVED_0697"
    const val ALL_FAILED_MARKER = "FAROL_COORDINATE_ALL_PROVIDERS_FAILED_0697"
    const val STALE_MARKER = "FAROL_COORDINATE_STALE_RESULT_DROPPED_0697"

    const val GLOBAL_DEADLINE_MS = 3_000L
    const val PLATFORM_DEADLINE_MS = 600L
    const val OSM_CONNECT_TIMEOUT_MS = 250
    const val OSM_READ_TIMEOUT_MS = 450
    const val GOOGLE_DEADLINE_MS = 1_100L

    fun budgetsFitGlobalDeadline(): Boolean =
        PLATFORM_DEADLINE_MS + OSM_CONNECT_TIMEOUT_MS + OSM_READ_TIMEOUT_MS + GOOGLE_DEADLINE_MS <= GLOBAL_DEADLINE_MS
}
