package br.com.mapeiaia.rotacerta

object RideAppLearningContract0702 {
    const val CONTRACT_MARKER = "RIDE_APP_LEARNING_RESILIENCE_0702"
    const val SHORTCUT_ID = "action_learn_ride_app"
    const val CONNECT_TIMEOUT_MS = 15_000
    const val READ_TIMEOUT_MS = 105_000
    const val STATUS_POLL_DELAY_MS = 1_500L
    const val STATUS_POLL_ATTEMPTS = 30
    const val MAX_TRANSPORT_RETRIES = 1

    const val APK_SELECTED = "RIDE_APP_LEARNING_APK_SELECTED_0702"
    const val DOSSIER_READY = "RIDE_APP_LEARNING_DOSSIER_READY_0702"
    const val LOCAL_CACHE_HIT = "RIDE_APP_LEARNING_LOCAL_CACHE_HIT_0702"
    const val REQUEST_SENT = "RIDE_APP_LEARNING_REQUEST_SENT_0702"
    const val BACKEND_STATUS = "RIDE_APP_LEARNING_BACKEND_STATUS_0702"
    const val BACKEND_CACHE_HIT = "RIDE_APP_LEARNING_BACKEND_CACHE_HIT_0702"
    const val TRANSPORT_FAILED = "RIDE_APP_LEARNING_TRANSPORT_FAILED_0702"
    const val RETRY = "RIDE_APP_LEARNING_RETRY_0702"
    const val PROFILE_SAVED = "RIDE_APP_LEARNING_PROFILE_SAVED_0702"
    const val FAILED = "RIDE_APP_LEARNING_FAILED_0702"
}
