// Compatibilidade final do leitor universal:
// - mantem a trava de idempotencia;
// - mantem os metadados e a sonda de validacao;
// - nao exige modelo de card cadastrado;
// - dois enderecos so liberam rota quando existem sinais reais de corrida.
//
// O contrato ativo e: localizar pelo menos dois enderecos reconheciveis, validar
// que a tela e uma oferta de corrida, usar o ultimo como destino e calcular ate
// o endereco definido pelo usuario. Fotos, documentos e listas de enderecos sem
// evidencia de corrida permanecem cinza e nao chamam geocodificacao/rotas.
apply(from = "patch-universal-two-address-idempotence.gradle.kts")
apply(from = "universal-overlay-runtime-metadata.gradle.kts")
apply(from = "in-app-bubble-immediate-state.gradle.kts")
apply(from = "universal-runtime-state-probe.gradle.kts")
apply(from = "universal-immediate-gray-clear.gradle.kts")
apply(from = "universal-runtime-stability-guard.gradle.kts")
apply(from = "universal-optional-model-contract.gradle.kts")
apply(from = "universal-flattened-address-boundary.gradle.kts")
apply(from = "universal-idempotence-compatibility.gradle.kts")
apply(from = "universal-probe-idempotence.gradle.kts")
apply(from = "universal-no-card-runtime-final.gradle.kts")
apply(from = "universal-no-card-anchor-compat.gradle.kts")
apply(from = "universal-no-card-process-anchor.gradle.kts")
apply(from = "universal-no-card-compile-repair.gradle.kts")
apply(from = "session-diagnostic-bootstrap.gradle.kts")
apply(from = "session-diagnostic-v2.gradle.kts")
apply(from = "session-diagnostic-retention.gradle.kts")
apply(from = "universal-overlay-self-window-fix.gradle.kts")
apply(from = "universal-poi-destination-boundary.gradle.kts")
apply(from = "universal-fast-read-runtime-0.1.108.gradle.kts")
apply(from = "universal-fast-read-runtime-0.1.109.gradle.kts")
apply(from = "universal-fast-read-runtime-0.1.110.gradle.kts")
apply(from = "universal-99-card-addresses-0.1.111.gradle.kts")
apply(from = "universal-99-card-continuation-0.1.111.gradle.kts")
apply(from = "universal-0.1.111-idempotence-compat.gradle.kts")
apply(from = "universal-ride-card-evidence-0.1.112.gradle.kts")
apply(from = "universal-fragmented-street-prefix-0.1.113.gradle.kts")
apply(from = "in-app-grouped-bubble-home-0.1.115.gradle.kts")
apply(from = "in-app-grouped-bubble-anchor-compat-0.1.115.gradle.kts")
apply(from = "in-app-grouped-bubble-navigation-compat-0.1.115.gradle.kts")
apply(from = "bubble-instant-drag-0.1.116.gradle.kts")
apply(from = "bubble-resource-shortcuts-runtime-0.1.117.gradle.kts")
apply(from = "bubble-shortcut-legacy-click-compat-0.1.117.gradle.kts")
apply(from = "bubble-shortcut-navigation-0.1.117.gradle.kts")
apply(from = "professional-bubble-home-0.1.118.gradle.kts")
apply(from = "version-0.1.101.gradle.kts")
apply(from = "version-0.1.102.gradle.kts")
apply(from = "version-0.1.103.gradle.kts")
apply(from = "version-0.1.104.gradle.kts")
apply(from = "version-0.1.105.gradle.kts")
apply(from = "version-0.1.106.gradle.kts")
apply(from = "version-0.1.107.gradle.kts")
apply(from = "version-0.1.108.gradle.kts")
apply(from = "version-0.1.109.gradle.kts")
apply(from = "version-0.1.110.gradle.kts")
apply(from = "version-0.1.111.gradle.kts")
apply(from = "version-0.1.112.gradle.kts")
apply(from = "version-0.1.113.gradle.kts")
apply(from = "version-0.1.114.gradle.kts")
apply(from = "version-0.1.115.gradle.kts")
apply(from = "version-0.1.116.gradle.kts")
apply(from = "version-0.1.117.gradle.kts")
apply(from = "version-0.1.118.gradle.kts")
