#!/usr/bin/env python3
from pathlib import Path
import sys

SOURCE = Path(sys.argv[1]).resolve()
BASE = Path(__file__).with_name("apply_stage47_r4_step7_clean_occupancy.py")
if not BASE.is_file():
    raise SystemExit(f"missing base clean occupancy patcher: {BASE}")

# The first clean-occupancy patcher tried to recalculate local+external occupancy
# inside a text fragment generated by the previous Step7 patcher. That anchor is
# unnecessarily brittle. Occupancy belongs to the physical-consolidation phase,
# after mirrors/subsegments are known, so omit only that text rewrite and keep all
# other clean UI / authenticated passenger evidence changes unchanged.
source = BASE.read_text(encoding="utf-8")

# The base patcher intentionally splits the sentence across two Kotlin comment
# lines ("A same" + "date/time..."). Its original static guard searched for the
# impossible contiguous phrase. Normalize only that guard before executing it.
legacy_guard = '"same date/time alone is NEVER enough"'
stable_guard = '"date/time alone is NEVER enough"'
if source.count(legacy_guard) != 1:
    raise SystemExit(f"clean occupancy v2 legacy static guard count={source.count(legacy_guard)}")
source = source.replace(legacy_guard, stable_guard, 1)

fragile = '''once(\n    COLLECTOR,\n    \'\'\'                    minimumOccupiedSeats = maxOf(local.minimumOccupiedSeats, external.minimumOccupiedSeats),\\n                    maximumOccupiedSeats = maxOf(local.maximumOccupiedSeats, external.maximumOccupiedSeats),\\n                    sourcePassengerSeats = mergeSourceSeats(local.sourcePassengerSeats, external.sourcePassengerSeats),\\n\'\'\',\n    \'\'\'                    minimumOccupiedSeats = mergeSourceSeats(local.sourcePassengerSeats, external.sourcePassengerSeats).values.sum(),\\n                    maximumOccupiedSeats = mergeSourceSeats(local.sourcePassengerSeats, external.sourcePassengerSeats).values.sum(),\\n                    sourcePassengerSeats = mergeSourceSeats(local.sourcePassengerSeats, external.sourcePassengerSeats),\\n\'\'\',\n    "merged real physical occupancy",\n)\n'''
if source.count(fragile) != 1:
    raise SystemExit(f"clean occupancy v2 fragile block count={source.count(fragile)}")
source = source.replace(fragile, "", 1)

previous_argv = sys.argv
try:
    sys.argv = [str(BASE), str(SOURCE)]
    namespace = {"__name__": "__main__", "__file__": str(BASE)}
    exec(compile(source, str(BASE), "exec"), namespace)
finally:
    sys.argv = previous_argv

# Kotlin 1.x compatibility: a member extension used as prefs::getBooleanTrue is
# prohibited (member + extension reference). Use the SharedPreferences API
# directly and remove the helper. This is behavior-identical and compile-safe.
timeline_ui = SOURCE / "app/src/main/java/br/com/mapeiaia/rotacerta/trips/TripTimelineUi.kt"
ui_text = timeline_ui.read_text(encoding="utf-8")
old_archive_check = '''    fun isArchived(entry: TripTimelineEntry): Boolean = aliases(entry).any(prefs::getBooleanTrue)\n'''
new_archive_check = '''    fun isArchived(entry: TripTimelineEntry): Boolean = aliases(entry).any { key -> prefs.getBoolean(key, false) }\n'''
if ui_text.count(old_archive_check) != 1:
    raise SystemExit(f"archive boolean compatibility anchor count={ui_text.count(old_archive_check)}")
ui_text = ui_text.replace(old_archive_check, new_archive_check, 1)
old_archive_helper = '''    private fun android.content.SharedPreferences.getBooleanTrue(key: String): Boolean = getBoolean(key, false)\n'''
if ui_text.count(old_archive_helper) != 1:
    raise SystemExit(f"archive boolean helper count={ui_text.count(old_archive_helper)}")
ui_text = ui_text.replace(old_archive_helper, "", 1)
timeline_ui.write_text(ui_text, encoding="utf-8")

consolidator = SOURCE / "app/src/main/java/br/com/mapeiaia/rotacerta/trips/TripPhysicalRideConsolidator.kt"
text = consolidator.read_text(encoding="utf-8")

# Recalculate even when the adapter already collapsed local+BlaBla into one card.
# This is what makes PRIVATE 1 + BLABLACAR 3 = 4 physical occupants, while an
# existing BLABLACAR mirror remains max(known, collected), not 3+3.
old = '''        if (entriesRaw.size < 2) return validate(entriesRaw, geo)\n'''
new = '''        if (entriesRaw.size < 2) return validate(entriesRaw.map(::recalculateOccupancy), geo)\n'''
if text.count(old) != 1:
    raise SystemExit(f"single-card occupancy recalculation anchor count={text.count(old)}")
text = text.replace(old, new, 1)

old = '''        if (group.size == 1) return group.single().copy(\n            issues = group.single().issues - setOf(TripTimelineIssue.PHYSICAL_CONFLICT, TripTimelineIssue.PROFILE_CONTINUITY, TripTimelineIssue.DUPLICATE),\n        )\n'''
new = '''        if (group.size == 1) return recalculateOccupancy(group.single()).copy(\n            issues = group.single().issues - setOf(TripTimelineIssue.PHYSICAL_CONFLICT, TripTimelineIssue.PROFILE_CONTINUITY, TripTimelineIssue.DUPLICATE),\n        )\n'''
if text.count(old) != 1:
    raise SystemExit(f"single physical group recalculation anchor count={text.count(old)}")
text = text.replace(old, new, 1)

anchor = '''    private fun validate(entriesRaw: List<TripTimelineEntry>, geo: Map<String, TimelineGeoPoint>): List<TripTimelineEntry> {\n'''
helper = '''    private fun recalculateOccupancy(entry: TripTimelineEntry): TripTimelineEntry {\n        val occupied = entry.sourcePassengerSeats.values.sum()\n        if (entry.sourcePassengerSeats.isEmpty()) return entry\n        val cleanIssues = entry.issues - TripTimelineIssue.OVERBOOKING\n        val issues = if (entry.capacity > 0 && occupied > entry.capacity) cleanIssues + TripTimelineIssue.OVERBOOKING else cleanIssues\n        val status = if (entry.capacity > 0 && occupied >= entry.capacity) TripStatus.FULL else entry.status\n        return entry.copy(\n            minimumOccupiedSeats = occupied,\n            maximumOccupiedSeats = occupied,\n            status = status,\n            issues = issues,\n        )\n    }\n\n    private fun validate(entriesRaw: List<TripTimelineEntry>, geo: Map<String, TimelineGeoPoint>): List<TripTimelineEntry> {\n'''
if text.count(anchor) != 1:
    raise SystemExit(f"physical occupancy helper anchor count={text.count(anchor)}")
text = text.replace(anchor, helper, 1)

# Kotlin compatibility: use values() rather than the newer enum entries API.
text = text.replace("BookingSource.entries.mapNotNull", "BookingSource.values().mapNotNull")
consolidator.write_text(text, encoding="utf-8")

ui = timeline_ui.read_text(encoding="utf-8")
quick = (SOURCE / "app/src/main/java/br/com/mapeiaia/rotacerta/trips/TripQuickPassengerUi.kt").read_text(encoding="utf-8")
collector = (SOURCE / "app/src/main/java/br/com/mapeiaia/rotacerta/trips/TripBlaBlaCollector.kt").read_text(encoding="utf-8")
dynamic = (SOURCE / "app/src/main/java/br/com/mapeiaia/rotacerta/trips/BlaBlaDynamicAccounts.kt").read_text(encoding="utf-8")

for marker in ("Card(onClick = ::openCard", "Passageiros BlaBlaCar", "URGENTE", "+ Passageiro", "Arquivar"):
    if marker not in ui:
        raise SystemExit(f"clean timeline marker missing after v2: {marker}")
if "Gerenciar" in ui:
    raise SystemExit("redundant Gerenciar action returned to Timeline")
if "getBooleanTrue" in ui:
    raise SystemExit("archive helper incompatible with Kotlin compiler returned")
for marker in ("BookingSource.PRIVATE", "Sem vaga física neste trecho"):
    if marker not in quick:
        raise SystemExit(f"clean private passenger marker missing: {marker}")
for marker in ("booked_seats", "blablaPassengers = trip.passengers"):
    if marker not in collector:
        raise SystemExit(f"real BlaBla occupancy marker missing: {marker}")
for marker in ("/rides/offer/passenger/", "passengers: passengers", "const nameNode = document.querySelector('[data-testid*=\"profile-name\"], [data-testid*=\"driver-name\"]');"):
    if marker not in dynamic:
        raise SystemExit(f"authenticated passenger/identity marker missing: {marker}")

print("stage47_r4_step7_clean_occupancy_v2=PASS occupancy_after_consolidation=true local_plus_blablacar_sum=true same_source_mirror_max=true clean_cards=true manage_removed=true responsive_actions=true visible_passenger_names=true geo_merge=true overbooking_urgent=true archive_boolean_compat=true farol_touched=false")
