#!/usr/bin/env python3
from pathlib import Path
import sys

ROOT=Path(sys.argv[1]).resolve(); PKG=ROOT/'app/src/main/java/br/com/mapeiaia/rotacerta'; R=PKG/'FarolRuntimeAuthorityStage36.kt'; S=PKG/'LiveRideAccessibilityService.kt'
def once(t,o,n,l):
 c=t.count(o)
 if c!=1: raise SystemExit(f'{l}: expected 1 occurrence, got {c}')
 return t.replace(o,n,1)
r=R.read_text(); r=once(r,'    const val NO_TIMER_MARKER = "NO_TIMER_NO_SLEEP_NO_POLLING_STAGE36"\n','    const val NO_TIMER_MARKER = "NO_TIMER_NO_SLEEP_NO_POLLING_STAGE36"\n    const val STAGE40_PRESENCE_MARKER = "CURRENT_WINDOW_OR_RESUMED_ACTIVITY_PRESENCE_STAGE40"\n','marker')
a='        @Synchronized fun snapshot(): Snapshot = snapshotLocked()\n\n        private fun markPositiveLocked(pkg: String, foreground: Boolean) {\n'; n='''        @Synchronized\n        fun expireStalePresence(currentSelectedWindows: Set<String>): Snapshot {\n            if (!usageAccessGranted || selected.isEmpty()) { hardOffLocked("stage40_presence_prerequisite_off"); return snapshotLocked() }\n            val visible=currentSelectedWindows.mapNotNull(::normalizePackage).filterTo(LinkedHashSet()){it in selected}\n            val current=LinkedHashSet<String>(); current+=visible; current+=resumed.filter{it in selected}\n            if(current.isEmpty()){ hardOffLocked("stage40_no_current_selected_presence"); Metrics.increment("stage40PresenceExpired"); return snapshotLocked() }\n            val removed=armed.filter{it !in current}.toSet(); armed.retainAll(current); armed.addAll(current)\n            foregroundServices.removeAll(removed); seenForegroundServicePositive.removeAll(removed); activityStoppedAfterPositive.removeAll(removed); foregroundServiceStoppedAfterPositive.removeAll(removed)\n            if(!enabled) ensureOnLocked("stage40_current_presence"); reason="stage40_presence_reconciled"; Metrics.increment("stage40PresenceReconciled"); return snapshotLocked()\n        }\n\n        @Synchronized fun snapshot(): Snapshot = snapshotLocked()\n\n        private fun markPositiveLocked(pkg: String, foreground: Boolean) {\n'''; r=once(r,a,n,'expire'); R.write_text(r)
s=S.read_text(); a='    private fun refreshReadingActivationStage26(\n'; n='''    private fun currentSelectedWindowPackagesStage40(selectedStage40:Set<String>):Set<String> =\n        runCatching{windows}.getOrDefault(emptyList()).mapNotNull{w->safeNodePackageName0185(runCatching{w.root}.getOrNull())}.filterTo(LinkedHashSet()){it in selectedStage40}\n\n'''+a; s=once(s,a,n,'window helper')
o='''        if (usageAccessStage36 && refreshUsageStage36) {\n            val evidenceStage36 = stage30PresenceState.readIncrementalUsage(selectedStage36, nowWallStage36)\n            stage30PresenceAuthority.applyUsageEvidence(evidenceStage36)\n            stage36RuntimeAuthority.applyUsageEvidence(evidenceStage36)\n        }\n\n        val runtimeStage36 = stage36RuntimeAuthority.snapshot()\n'''; n='''        if (usageAccessStage36 && refreshUsageStage36) {\n            val evidenceStage36 = stage30PresenceState.readIncrementalUsage(selectedStage36, nowWallStage36)\n            stage30PresenceAuthority.applyUsageEvidence(evidenceStage36)\n            stage36RuntimeAuthority.applyUsageEvidence(evidenceStage36)\n        }\n        if(windowBoundaryStage36 || windowsChangedStage36 || selectedEventStage36){\n            val currentSelectedWindowsStage40=currentSelectedWindowPackagesStage40(selectedNormalizedStage36).toMutableSet()\n            if(selectedEventStage36 && eventPackageNormalizedStage36!=null) currentSelectedWindowsStage40+=eventPackageNormalizedStage36\n            stage36RuntimeAuthority.expireStalePresence(currentSelectedWindowsStage40)\n        }\n\n        val runtimeStage36 = stage36RuntimeAuthority.snapshot()\n'''; s=once(s,o,n,'service reconcile'); S.write_text(s); print('stage40_presence=PASS')
